version: '3.7'
services:
  postgres:
      image: postgres:15.4
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=asset_management_backend
      ports:
        - '5434:5432'

      # postgresql://nodeProdUser:postgresPasswword@localhost:5434/asset_management_backend
